ARANGOPY_MAJOR_VERSION_NUMBER = 0
ARANGOPY_MINOR_VERSION_NUMBER = 2

ARANGOPY_SHORT_VERSION = (ARANGOPY_MAJOR_VERSION_NUMBER, ARANGOPY_MINOR_VERSION_NUMBER)
ARANGOPY_VERSION = (ARANGOPY_MAJOR_VERSION_NUMBER, ARANGOPY_MINOR_VERSION_NUMBER, 0, 'release')

def get_short_version():
    return '%s.%s' % (ARANGOPY_SHORT_VERSION)

def get_version():
    return '%s.%s.%s - %s' % (ARANGOPY_VERSION)